# Configure a multi-container architecture by separating frontend from backend and placing each in their own containers.
# To start (or restart): Use the command 'docker compose -p mazeio up --build'
# To stop: Use the command 'docker compose -p mazeio down'
# Note that docker-compose up never rebuilds an image. We can locally use docker-compose build to build the images if needed.
services:
  frontend:
    build: ./frontend
    ports:
      # Mapping of host port to container port
      - '3000:3000'
    container_name: frontend
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - "./frontend/:/app/"
      - /app/node_modules


