# Configure a multi-container architecture by separating frontend from backend and placing each in their own containers.
# To start (or restart): Use the command 'docker compose -p mazeio up --build'
# To stop: Use the command 'docker compose -p mazeio down'
# Note that docker-compose up never rebuilds an image. We can locally use docker-compose build to build the images if needed.
services:
  frontend:
    build: ./frontend
    env_file:
      - ./frontend/.env
    ports:
      # Mapping of host port to container port
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    container_name: frontend
    volumes:
      - ./frontend/:/app/
      - /app/node_modules

  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    container_name: backend
    volumes:
      - ./backend/:/app/
      - /app/node_modules


